export enum AuthSagaActions {
  GOOGLE_SIGN_IN_SAGA = 'GOOGLE_SIGN_IN_SAGA',
  FACEBOOK_SIGN_IN_SAGA = 'FACEBOOK_SIGN_IN_SAGA',
  SIGN_OUT_SAGA = 'SIGN_OUT_SAGA',
  CHECK_FIREBASE_USERS_SAGA = 'CHECK_FIREBASE_USERS_SAGA',
}
